name: Plain JS Website per FTP übertragen

on:
  repository_dispatch:
    types: [directus-update]
  workflow_dispatch: # Ermöglicht manuellen Start über die GitHub-Oberfläche

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v6

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3.2.1
        with:
          hugo-version: '0.165.0'

      - name: Build Site
        run: hugo --minify

      - name: Dateien per FTP hochladen
        uses: milanmk/actions-file-deployer@1.18
        with:
          remote-host: ${{ vars.SGL_FTP_SERVER }}
          remote-user: ${{ secrets.SGL_FTP_USERNAME }}
          remote-password: ${{ secrets.SGL_FTP_PASSWORD }}
          remote-protocol: "sftp"
          local-path: ./dist/ # Lädt die gebaute Website hoch
          remote-path: /
          sync: full
          #remote-path: / # Pfad bei FTP Hoster
