name: Plain JS Website per FTP übertragen

on:
  repository_dispatch:
    types: [directus-update]
  workflow_dispatch: # Ermöglicht manuellen Start über die GitHub-Oberfläche

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code auschecken
        uses: actions/checkout@v6

      - name: Seite bauen
        run: |
          mkdir ./dist
          cp -pr assets dist/
          cp -p index.html logo.png dist/

      - name: Dateien per FTP hochladen
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ vars.SGL_FTP_SERVER }}
          username: ${{ secrets.SGL_FTP_USERNAME }}
          password: ${{ secrets.SGL_FTP_PASSWORD }}
          local-dir: ./dist/ # Lädt die gebaute Website hoch
          server-dir: / # Pfad bei FTP Hoster
